---
- name: say thanks
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Thank you, z/OS lover!"
      when:
        - ansible_eda is defined
        - "{{ ansible_eda.event.message }} is search ('z/OS')"
    - debug:
        msg: "Thank you!"
      when:
        - ansible_eda is defined
        - "{{ ansible_eda.event.message }} is not search ('z/OS')"